// src/ulde/types/frame/ulde-frame.types.ts

import { ULDEDiagnostic } from "@ulde/types/diagnostic";
import { ULDELifecyclePhaseTiming } from "@ulde/types/lifecycle";
import { ULDEPluginTiming } from "@ulde/types/timing";

// ---------------------------------------------------------
// ULDE Frame
// Use ULDEFrame for introspection, not for endering
//---------------------------------------------------------

export interface ULDEFrame {
  id: string;
  timestamp: number;
  lifecyclePhaseTimings: ULDELifecyclePhaseTiming[];
  pluginTimings: ULDEPluginTiming[];
  diagnostics: ULDEDiagnostic[] //warning or error generated by ULDE
}
