// src/ulde/types/frame/ulde-frame.types.ts

import { ULDELifecyclePhaseTiming } from "@ulde/types/lifecycle";
import { ULDEPluginTiming } from "@ulde/types/timing";
import { ULDEDiagnostic } from "@ulde/types/diagnostic";

// ---------------------------------------------------------
// ULDE Frame
// ---------------------------------------------------------

export interface ULDEFrame {
  id: string;
  timestamp: number;
  lifecyclePhases: ULDELifecyclePhaseTiming[];
  pluginTimings: ULDEPluginTiming[];
  diagnostics: ULDEDiagnostic[] //warning or error generated by ULDE
}
