// src/ulde/types/frame/ulde-frame.types.ts

import { ULDELifecyclePhaseTiming } from "@ulde/types/lifecycle";
import { ULDEPluginTiming } from "@ulde/types/timing";

/** runtime measurements
 * role: execution run record, and a frame is not analytics, so a frame is one exxecution measurement
 * rule: one frame = one execution
 */
export interface ULDEFrame {
  id: string;
  timestamp: number;
  lifecyclePhaseTimings: ULDELifecyclePhaseTiming[];
  pluginTimings: ULDEPluginTiming[];
  // diagnostics: ULDEDiagnostic[] //warning or error generated by ULDE
}
